# [package]
# name = "pf2e-csheet"
# version = "0.1.0"
# authors = ["Cassie Meharry <cassie@prophetessof.tech>"]
# edition = "2018"

[workspace]
members = [
    "aon2e-scraper",
    "pf2e-csheet-backend",
    "pf2e-csheet-frontend",
    "pf2e-csheet-shared",
]
